### ISSUE TITLE
Discourse-Adsense on Docker installation

### ISSUE THREAD

**Issue by skeith** [discoursehosting/discourse-adsense#5]
Added the plugin through app.yml

```
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/discoursehosting/discourse-adsense.git
```

then apply the change with
`/var/docker/launcher rebuild app`
but the adsense menu is still not added to admin page.

anything I missed?

Discourse version 0.9.9.8
